### ISSUE TITLE
CORS-Error when socket.io-instance is set to socketio.0 instead of integrated

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.socketio#11]
Using a socket.io connection via conn.js
All working fine, as long as web-adapter is configured to use integrated socket.io.
When chosing socketio.0 the following error appears in the browsers-console (chrome) and connection fails:

Access to XMLHttpRequest at 'http://192.168.10.69:8082/socket.io/?key=nokey&EIO=3&transport=polling&t=MljDYfK' from origin 'http://192.168.10.69:8081' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

(Also connection fails, when "force web-socket" is set).

Is there any known way to fix this?

Many thanks!

**Comment by Apollon77** [comment]
This is a web issue. And there is already one ticket about cors headers. We should merge those.
