### ISSUE TITLE
No ioBroker.vis state updates after socketio v6 (6.0.1) upgrade

### ISSUE THREAD

**Issue by jens-maus** [ioBroker/ioBroker.socketio#115]
**Describe the bug**  
After having updated to ioBroker.socketio v6 (6.0.1) together with ioBroker.web v5 (5.0.0) my VIS powered iOS display terminals stopped to display immediate state updates. For example, when opening a door a state update is usually displayed within several seconds.

After the upgrade to socketio v6 and web v5 these immediate state updates stopped immediately. Performing a downgrade to socketio v5 and web v4 instantly solves this issue and state updates are immediately displayed again.

**To Reproduce**  
1. Display a VIS page on an iOS (15.x) device and monitor state updates
2. Perform a state change (e.g. open the door)
3. See that no state updates are shown within VIS.

**Expected behavior**  
State updates should immediately propagate to a VIS terminal, which does not seem to be the case anymore.

**Screenshots & Logfiles**  
n/a

**Versions:**  
 - Adapter version: 6.0.1
 - JS-Controller version: 4.0.23
 - Node version: v14.19.3
 - Operating system: Ubuntu 20.04

**Additional context**  
n/a

**Comment by Apollon77** [comment]
Please try web 5.0.1 and socketio 6.0.2 ... see also https://forum.iobroker.net/topic/55027/nach-update-von-socket-io-und-web-server

**Comment by GermanBluefox** [comment]
@jens-maus 
Is this issue still actual?

**Comment by jens-maus** [comment]
Nope, works now! Thanks for asking.
