### ISSUE TITLE
Authentication stopped working

### ISSUE THREAD

**Issue by EvilEls** [ioBroker/ioBroker.socketio#116]
With version 6.0.1 Authentication is no longer working. 

Not working:
![grafik](https://user-images.githubusercontent.com/29343914/169517157-aea9fc7f-6eab-4b19-9051-a450a8f1cbc5.png)

Working:
![grafik](https://user-images.githubusercontent.com/29343914/169517100-1bfdca0d-ee99-4638-85e5-f8ee9da3156f.png)

```
socketio.0 | 2022-05-20 13:13:16.499 | error | socket.io [use] Cannot detect user
socketio.0 | 2022-05-20 13:13:13.325 | error | socket.io [use] Cannot detect user
socketio.0 | 2022-05-20 13:13:11.137 | info | Secure socket.io server listening on port 8084
socketio.0 | 2022-05-20 13:13:11.044 | info | starting. Version 6.0.2 in /opt/iobroker/node_modules/iobroker.socketio, node: v14.19.2, js-controller: 4.0.23
```

**Comment by Apollon77** [comment]
Works again in 6.1.x?

**Comment by EvilEls** [comment]
Auth is working again with
Version 6.1.4 in /opt/iobroker/node_modules/iobroker.socketio, node: v14.19.2, js-controller: 4.0.23
Thank you very much!
