### ISSUE TITLE
Trying to use this adapter on iOS

### ISSUE THREAD

**Issue by georgbachmann** [ioBroker/ioBroker.socketio#12]
I would love to try out this adapter to play around a little bit on my iPhone.
I am just stuck at the very beginning, cause it seems as if I don't get any events at all?
I have a connection established and am listening to all events, but when I now switch on or off a light at home, not message is sent to my iPhone.

    let manager = SocketManager(socketURL: URL(string: "http://192.168.1.101:8084")!, config: [.log(false), .compress])
    socket.on(clientEvent: .connect) { data, ack in
        print("socket connected")
    }
    socket.onAny { event in
        print("something \(event)")
    }

I see `socket connected` but never `something`

I am very new to the whole socket.io thing, so any hints would be greatly appreciated
Is there anything I need to enable in ioBroker in order to get state updates?

**Comment by Apollon77** [comment]
You need to subscribe to state updates first, else no updates are sent to you :-) It seems that this is missing in the docs.
So send "subscribe" as command with a pattern for the states you want to receive ("*" for everything or other name pattern for more specific patterns).

**Comment by Apollon77** [comment]
PS: in fact her eis the code that handles subscribes: https://github.com/ioBroker/ioBroker.socketio/blob/master/lib/socket.js#L1203

**Comment by georgbachmann** [comment]
Thank you for your help! Awesome! Now I get updates! Very nice!

     socket.emit("subscribe", with: ["hm-rpc.1.NEQ0137169.1.STATE"])

Can you just tell me how I should be able to read a state? Tried it with `getStates` and then the name of my device, but I don't get anything from that?

Anyway! Thank you very much and I guess I just need to do some playing around :)

**Comment by Apollon77** [comment]
getStates without any parameter should get you ALL states, else you need to provide a pattern string, so not array as you used above but the string like "hm-rpc.1.NEQ0137169.1.*" or such
