### ISSUE TITLE
File States can result in Payload exceeding

### ISSUE THREAD

**Issue by theimo1221** [ioBroker/ioBroker.socketio#126]
**Describe the bug**  
Having some file states (`common.type = 'file'`) a call for `_socket.emit('getStates', '*')` might crash on `websocket error max payload size exceeded`

**To Reproduce**  
1. Have some larger livestream mp4 file states from e.g. Ring Adapter
2. Try to get all states

**Expected behavior**  
Probably the easiest solution would be to exclude any file states from any call which has more than x states as a target.
Or add an option in `getStates` to exclude certain state types.

Generally giving a precise error by calculating payload before sending might be beneficial as the user must extract it from underlying websocket error in `_socket.on('error')'`

**Versions:**  
 - Adapter version: v6.1.10
 - JS-Controller version:  4.0.23
 - Node version: v16.16.0

**Comment by Apollon77** [comment]
Puuhh ... in worst case this is a js-controller issue :-(

**Comment by theimo1221** [comment]
Today this crashed my whole system again.

@Apollon77 As per your worry, should I open an issue there?

**Comment by Apollon77** [comment]
Yes please ... and link here
