### ISSUE TITLE
onObjectChange callback is not called for deletes

### ISSUE THREAD

**Issue by aortmannm** [ioBroker/ioBroker.socketio#127]
The onObjectChange callback is not called when a state is deleted like it's documented in the readme.

onObjectChange: function (id, obj)     {}, // optional - called if content of some object is changed, new object created or object was deleted (obj = null)

**Comment by Apollon77** [comment]
Are you sure you do not mix stuff ?

"deleting a state" is something else then "deleting an object"

**Comment by aortmannm** [comment]
Sorry you are right, my mistake I close the Issue
