### ISSUE TITLE
web Adapter nicht erreichbar mit 6.2.0

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.socketio#138]
web.0 nutzt bei mir ein Lets Encrypt Zertifikat für eine myfritz.net Domain mit Portfreigabe für 443:
![image](https://user-images.githubusercontent.com/39678667/200803926-5ac28703-08d2-4de0-a005-8ebe25dfcc9e.png)

Nach Update von socketio 6.1.10 auf 6.2.0 und ws 2.1.5 auf 2.2.1, funktioniert der Zugriff nicht mehr. Im Browser kommt nur:
![socketio_6 2 0](https://user-images.githubusercontent.com/39678667/200803636-c98c047f-4aa8-4874-b958-30fa6b2247b3.jpg)

**Comment by GermanBluefox** [comment]
Was wird im Log von web/socketio angezeigt?

**Comment by Diginix** [comment]
Ich habe (leider) direkt wieder ein Snapshot Rollback auf die Vorgängerver. gemacht damit alles wieder funktioniert.
Müsste ich heute bei Gelegenheit nochmal hochziehen um erneut ein Log zu haben.

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/200808875-e2ecbc74-cc53-460f-b046-950fbd6ed43f.png)
Ich kann das Problem nicht reproduzieren

**Comment by Apollon77** [comment]
Do you use lets encrypt with an external domain?

**Comment by Diginix** [comment]
Die web.1 Instanz für lokalen Zugriff funktionierte auch weiterhin.
Wie gesagt ich habe auch über web.0 Zugriff von außen mit validem SSL Cert.

**Comment by GermanBluefox** [comment]
@Diginix hast du was neues? Logs?

**Comment by Diginix** [comment]
Leider noch nicht. Am Wochenende kann ich das Update nochmal machen und alles loggen.

**Comment by Diginix** [comment]
Soeben das Update noch mal durchgeführt und nachdem web.0 und web.1 mehrfach automatisch neu gestartet wurden, funktioniert der Zugriff auch von außen mit FQDN+SSL Cert. Ich vermute dass web.0 beim ersten Update nicht sauber durchgestartet war und deswegen der Zugriff nicht mehr möglich war.
