### ISSUE TITLE
Enums

### ISSUE THREAD

**Issue by swissglider** [ioBroker/ioBroker.socketio#14]
Is it possible that with getObjects and getObject also to get all enums and not only rooms ?
Just change in socket.io on row 857 'rooms' to '*' and add on 851 also '*'

This would be very helpfull to get also functions enum etc.

**Comment by GermanBluefox** [comment]
Additionally call only this and you have everything you need. 
```
socket.getObjectView('system', 'enum', {startkey: '', endkey:'\u9999'}, (err, doc) => {
    doc.rows.forEach(item => console.log(JSON.stringify(item.value)));
});
```
