### ISSUE TITLE
upgrade error 25

### ISSUE THREAD

**Issue by fs-plugins** [ioBroker/ioBroker.socketio#165]
$ iobroker upgrade web@6.1.1
Update web from @6.1.0 to @6.1.1
host.fs-ubuntu2022 Adapter "system.adapter.web.0" is stopped.
host.fs-ubuntu2022 Adapter "system.adapter.web.1" is stopped.
Installing iobroker.web@6.1.1... (System call)
host.fs-ubuntu2022 Cannot install iobroker.web@6.1.1: 128
ERROR: Process exited with code 25

same with web-socket, webserver, socket.io

**Comment by Apollon77** [comment]
Run "iob fix" and try again
