### ISSUE TITLE
changelog v3.0.0: obviously a copy/paste mistake

### ISSUE THREAD

**Issue by HGlab01** [ioBroker/ioBroker.socketio#22]
Changelog for version 3.0.0 is "(Apollon77) upgrade all dependencies, especially socketio to current version! This might break ipad 1/2 devices".
Seams to be a copy/paste mistake? I guess it is e.g. adapter core 22.1 and iobroker 2.2.1

**Comment by Apollon77** [comment]
what makes you thing it is an error? Exactly this it's about. socketio library was upgraded and this can cause older devices to not work anymore with older browsers

**Comment by HGlab01** [comment]
but saying "especially socketio" as description of socketio is misleading, isn't?
So for me the message is: socketio is dependent from socketio, so update socketio when updating socketio. 
Did I misinterpret the message?

**Comment by Apollon77** [comment]
socketio is a nodejs library used in this adapter and this library was updated ... the name of the lib is the same as the adapter, but still correct :-)
