### ISSUE TITLE
Warnings from socket.io in web.0 instance

### ISSUE THREAD

**Issue by oke24** [ioBroker/ioBroker.socketio#24]
When starting web.0 with socket.io enabled as external cache I get a tons of warnings in my logfile

`readFile will not read this file (index.html) in future versions: socket.io is not an object of type "meta"`

So I have to switch back to internal cache.

**Comment by Apollon77** [comment]
Please try „iobroker upload socketio“

**Comment by oke24** [comment]
Thanks for quick reply! But also after „iobroker upload socketio“ there are plenty of these warnings, first from readfilem then from webserver

![image](https://user-images.githubusercontent.com/46261409/80833317-949cc200-8bee-11ea-8cb9-e5669a1820ac.png)

**Comment by Apollon77** [comment]
And iobroker upload web

?

**Comment by oke24** [comment]
with " iobroker upload web" the warnings from readFile are gone, but web.0 warning are still there

![image](https://user-images.githubusercontent.com/46261409/80834063-47b9eb00-8bf0-11ea-93bf-914a96bed184.png)

**Comment by Apollon77** [comment]
Kk I check later. For now ignore them please. 

Do you use integrated socketio now or the one from separate adapter?

**Comment by oke24** [comment]
I switched back to the integrated socketio when the warnings apperar after update to socket.io version 3.0.3 .

**Comment by Apollon77** [comment]
Also in js.controller 3.1.x they should be gone

**Comment by oke24** [comment]
[solved] thank you very much !
