### ISSUE TITLE
Cannot load socket.io.js

### ISSUE THREAD

**Issue by Negalein** [ioBroker/ioBroker.socketio#26]
seit Javascript 4.6.10 kommt obige Meldung und endet in einem Dauerladesymbol von Javascript.

**Comment by Apollon77** [comment]
JavaScript hat mit dem Adapter nichts  zu tun

**Comment by Sascha321** [comment]
Hallo ich bekomme die Meldung auch, woran liegt es denn dann?
Node-Version:	10..20.1
Nodejs-Version: 10.20.1
NPM-Version:	6.14.4
JS Skript Engine 4.6.17

**Comment by Apollon77** [comment]
Welche Admin Version?

**Comment by Sascha321** [comment]
Hallo
Ja es lag an der Admin Version, nach dem ich die neue Version installiert hatte ging es, Danke.

**Comment by Dexdar** [comment]
Hi zusammen,

ich habe eine ähnliches problem. Beim öffnen einer Istanz bekomme ich folgenden Fehler: Cannot load socket.io.js!
Zudem seehe ich im Log folgendes: 
![Fehlermeldung](https://user-images.githubusercontent.com/112970809/188695183-694b9e9c-c211-47d4-9f3f-0019a676358c.jpg)

Ich hab den ioBroker zudem nochmals neu installiert, jedoch ohne Erfolg. Ich hoffe ihr könnt mir weiterhelfen.

Viele Grüße

**Comment by Apollon77** [comment]
@Dexdar Do you think it makes sense to post into an issue that is closed since more then 2 years?

Please open a new one with all version details and info on affected adapters and such
