### ISSUE TITLE
3.0.13 very slow

### ISSUE THREAD

**Issue by EvilEls** [ioBroker/ioBroker.socketio#30]
I'm using the adapter for my self made visualization utilizing the script from /example/.
With version 3.0.12 on connect all states are submitted in less than a second.
3.0.13 appears to send only small batches of states every few seconds. So the page appears to load VERY slow.

**Comment by Apollon77** [comment]
does that mean that 3.0.12 ok ist and works?

**Comment by EvilEls** [comment]
> 
> 
> does that mean that 3.0.12 ok ist and works?

yes, with 3.0.12 it is working again.
