### ISSUE TITLE
Socket.io and conn.js and example index.html: No states

### ISSUE THREAD

**Issue by Kamikaze99** [ioBroker/ioBroker.socketio#32]
**Describe the bug**  
i use socket.io and conn.js and index.html out from example directory.
Since socket.io Version 2.1.2 all worked fine and i have got about 8000 states from iobroker, when i use "Force Websocket" and modify index.html to:
```
servConn.init(
--
  {
   name: 'mobile.0', // optional - default 'vis.0'
   connLink: 'http://localhost:8084', // optional URL of the socket.io adapter
   socketSession: '', // optional - used by authentication
   socketForceWebSockets: true, // Eintrag wegen fehlerhafter Kommunikation, Adapter wurde auch auf Websocket eingestellt
   },
```

today i updated socket.io to version 3.0.13 and get no states.
The discussion in iobroker forum let me got the idea to install different versions. 
So i could see, Version 3.0.9 up to 3.0.12 work fine, only version 3.0.13 get no states.
```
onConnChange: function (isConnected) {
      if (isConnected) {
        console.log('connected');
        servConn.getStates(function (err, _states) {
          var count = 0;
          for (var id in _states) {
            count++;
          }
          console.log('Received ' + count + ' states.');
          states = _states;
        });
      } else {
        console.log('disconnected');
      }
```

i get the message "connected" and not more.

**Comment by dot-not** [comment]
Same here. Let me know if you need any further debug info.

**Comment by EvilEls** [comment]
#30 
same

**Comment by Apollon77** [comment]
does 3.0.12 is ok and works?

**Comment by Apollon77** [comment]
There was a change in one method signature and conn.js needs to be updated ... I think the example was forgotten :-(

**Comment by Apollon77** [comment]
PS: I expect a change like https://github.com/ioBroker/ioBroker.vis/commit/6e4c6a0df2405fce50a00785d4d3e4ea25c55b43#diff-cac666adcc96f99ac47921351950e570R500 is needed

**Comment by EvilEls** [comment]
> 
> 
> does 3.0.12 is ok and works?

Yes, 3.0.12 is working fine.

**Comment by Kamikaze99** [comment]
The patch of conn.js solve my problem, but i think ther is a syntax error in the description.
`//socket.io
    if (this._socket === null) {
      console.log('socket.io not initialized');
      return;
    }
    this._socket.emit('getVersion', function (version) {
      if (callback) callback(version);
    });
    this._socket.emit('getVersion', function (error, version) {
      callback && callback(version || error);
    });`

with this short modification i got all my states.

Thank you.

**Comment by Apollon77** [comment]
i tried to fix it ... https://github.com/ioBroker/ioBroker.socketio/commit/67ec58299dedcf67a533978ae79a564508d90928 (editor changed line endings, so compare with ignoring them ;-)

**Comment by blumfisch** [comment]
I tried the updated conn.js with the example index.html.
It gets all states when I do NOT use  "only web sockets".
When I DO click "only use web sockets" in the socket.io-Adapter (3.0.13) I get this error in Chrome console log:

`GET http://192.168.178.101:8084/socket.io/?key=nokey&EIO=3&transport=polling&t=NOHOriG 400 (Bad Request)`
and 
`connUpdated.js:284 Uncaught ReferenceError: $ is not defined
    at r.<anonymous> (connUpdated.js:284)
    at r.emit (index.js:83)
    at r.emit (index.js:83)
    at r.emitAll (index.js:83)
    at r.<anonymous> (index.js:83)
    at r.emit (index.js:83)
    at r.onError (index.js:83)
    at o.<anonymous> (index.js:83)
    at o.r.emit (index.js:83)
    at o.r.onError (index.js:83)`

Maybe I'm doing something wrong? But I'm just using the examples...

**Comment by Apollon77** [comment]
This error is something different (a missing check) ... added with latest commit

**Comment by blumfisch** [comment]
Thanks for the quick reply!

With the latest commit AND "Force Websockets" enabled I still get part of the error.
 
` GET http://192.168.178.101:8084/socket.io/?key=nokey&EIO=3&transport=polling&t=NOK30TR 400 (Bad Request)

  | i.create | @ | index.js:83
-- | -- | -- | --
  | i | @ | index.js:83
  | o.request | @ | index.js:83
  | o.doPoll | @ | index.js:83
  | r.poll | @ | index.js:83
  | r.doOpen | @ | index.js:83
  | r.open | @ | index.js:83
  | r.open | @ | index.js:83
  | r | @ | index.js:83
  | r | @ | index.js:83
  | r.open.r.connect | @ | index.js:83
  | r.open.r.connect | @ | index.js:83
  | (anonymous) | @ | connUpdated.js:151
  | setInterval (async) |   |  
  | reconnect | @ | connUpdated.js:149
  | (anonymous) | @ | connUpdated.js:354
  | r.emit | @ | index.js:83
  | r.emit | @ | index.js:83
  | r.emitAll | @ | index.js:83
  | (anonymous) | @ | index.js:83
  | r.emit | @ | index.js:83
  | r.onError | @ | index.js:83
  | (anonymous) | @ | index.js:83
  | r.emit | @ | index.js:83
  | r.onError | @ | index.js:83
  | (anonymous) | @ | index.js:83
  | r.emit | @ | index.js:83
  | i.onError | @ | index.js:83
  | (anonymous) | @ | index.js:83
  | setTimeout (async) |   |  
  | hasXDR.e.onreadystatechange | @ | index.js:83
  | XMLHttpRequest.send (async) |   |  
  | i.create | @ | index.js:83
  | i | @ | index.js:83
  | o.request | @ | index.js:83
  | o.doPoll | @ | index.js:83
  | r.poll | @ | index.js:83
  | r.doOpen | @ | index.js:83
  | r.open | @ | index.js:83
  | r.open | @ | index.js:83
  | r | @ | index.js:83
  | r | @ | index.js:83
  | r.open.r.connect | @ | index.js:83
  | r | @ | index.js:83
  | r | @ | index.js:83
  | r | @ | index.js:83
  | init | @ | connUpdated.js:259
  | (anonymous) | @ | index.html:19

`

**Comment by blumfisch** [comment]
More info:
When I use the newest conn.js example WITHOUT "force-websockets"
- I get all states.
- And the answer from 
"http://192.168.178.101:8084/socket.io/?key=nokey&EIO=3&transport=polling&t=NOKYELX" 
is
98:0{"sid":"CzzOS2oQ_5eYmkhQAAAH","upgrades":["websocket"],"pingInterval":120000,"pingTimeout":30000}2:40

Seems good.

However, if I check "force web-sockets" in the socket.io Adapter 3.0.13
- I dont get any states, just the error message in chrome console.log.
- And the answer to  
"http://192.168.178.101:8084/socket.io/?key=nokey&EIO=3&transport=polling&t=NOKYELX" 
is
{"code":0,"message":"Transport unknown"}

I dont know if it's even a problem, since the first example seems to upgrade to sockets after it's first contact anyway. 
I have 5.000+ states which are loaded within a second. So it's pretty fast.

Just wanted to give additional feedback in case it is a bug.

**Comment by Apollon77** [comment]
Ok, with this I'm wout :-(

@GermanBluefox any idea?!

**Comment by ZeroQool007** [comment]
Same problem, need help please. thanks

**Comment by ZeroQool007** [comment]
> I tried the updated conn.js with the example index.html.
> It gets all states when I do NOT use "only web sockets".
> When I DO click "only use web sockets" in the socket.io-Adapter (3.0.13) I get this error in Chrome console log:
> 
> `GET http://192.168.178.101:8084/socket.io/?key=nokey&EIO=3&transport=polling&t=NOHOriG 400 (Bad Request)`
> and
> `connUpdated.js:284 Uncaught ReferenceError: $ is not defined at r.<anonymous> (connUpdated.js:284) at r.emit (index.js:83) at r.emit (index.js:83) at r.emitAll (index.js:83) at r.<anonymous> (index.js:83) at r.emit (index.js:83) at r.onError (index.js:83) at o.<anonymous> (index.js:83) at o.r.emit (index.js:83) at o.r.onError (index.js:83)`
> 
> Maybe I'm doing something wrong? But I'm just using the examples...

Where I find the conn.js? On ioBroker Server? thanks

**Comment by Apollon77** [comment]
example was updated https://github.com/ioBroker/ioBroker.socketio/blob/master/example/conn.js
