### ISSUE TITLE
setState: "ack:true" not working, is always ack:false

### ISSUE THREAD

**Issue by Mic-M** [ioBroker/ioBroker.socketio#33]
**Describe the bug**  
`ack:true` does not work for setState command, example: `conn.emit('setState', 'xyz', {val: false, ack:true}` and it always sets ack:false

See for example this node.js module as an example: https://github.com/Jey-Cee/iobroker-drones/tree/iobroker-drones-promises-test
Jey-Cee verified and confirmed this issue.

**To Reproduce**  
Send a setState command with ack:true, like `{val: false, ack:true}`

**Expected behavior**  
ack:true is working

**Screenshots & Logfiles**  
N/A

**Versions:**  
 - Adapter version: 3.0.13
 - JS-Controller version: 3.1.6
 - Node version: 12.16.1
 - Operating system: Linux and Windows

**Comment by Apollon77** [comment]
I also traced it down to controller but the code there looks ok ... so need to take another look

**Comment by foxriver76** [comment]
I am also not able to reproduce it in FE, can you please provide a minimal non working example. Please do not use Admin Objects Tab to validate if the state is set with ack or not. Use `iob state get _your-state__` via cli.

**Comment by Mic-M** [comment]
Thanks @Apollon77 and @foxriver76 
In my latest test it actually worked with ack:true. I reached out to Jey Cee and he will test as well, and he will test as well.
We will get back to you within the next few days.
