### ISSUE TITLE
extendObject not working at all

### ISSUE THREAD

**Issue by Mic-M** [ioBroker/ioBroker.socketio#34]
**Describe the bug**  
extendObject is not working at all: 
Example: the debugger reaches line 44, but does never go into 46 or 48. And the object does not change at all.

![image](https://user-images.githubusercontent.com/39859059/96029832-7bfe2c80-0e5b-11eb-9904-9c2ce5738f42.png)

**To Reproduce**  
Try extendObject to extend an object.

**Expected behavior**  
It works fine within JS adapter, and this is expected for socketio as well:
```js
// Test: ExtendObject
const id = '0_userdata.0.example_state';
extendObject(id, {native: {hallo:'Welt'}}, (err)=>{
    if (err) {
        console.error(`Error - conn.emit extendObject '${id}': ${err}`);
    } else {
        console.log(`conn.emit extendObject '${id}': We are in callback and no error occurred`);
    }
});

```

**Screenshots & Logfiles**  
N/A

**Versions:**  
 - Adapter version: 3.0.13
 - JS-Controller version: 3.1.6
 - Node version: 12.16.1
 - Operating system: Linux and Windows

**Additional context**  
See full node.js test code here: (sorry, spoiler seems to be not working here to hide this)
```js
'use strict';

// Test ioBroker socket-io Adapter

const ioClient = require('socket.io-client');
let conn; // ioBroker socket io connection

// IP address and port from ioBroker socket-io adapter instance settings
const ip = '10.10.0.165';
const port = 9090;

// Object id, type state, to be created for testing - we add timestamp since we want to create state on every start
const id = '0_userdata.0.TEST-socket-io.' + Date.now().toString();


main();
async function main() {

    try {

        console.log(`START: Test ioBroker's socketio adapter`);        

        // Connect with ioBroker socket-io adapter
        conn = ioClient.connect('http://' + ip + ':' + port);           

        // Once connected:
        conn.on('connect', async ()=>{

            try {
                
                console.log(`We are connected with ioBroker socketio adapter`);

                // create test object
                if (! await getObjectAsync(id)) {
                    await setObjectAsync(id, {'type': 'state', 'common': {name:'TEST', role:'state', read:true, write:true, type:'string' }, 'native': {}});
                    console.log(`Test object '${id}' created.`);
                } else {
                    throw(`TEST - object '{id}' already exists, but we want a fresh one`);
                }

                // setTimeout for Test.
                setTimeout(()=>{
                    // Test: ExtendObject
                    conn.emit('extendObject', id, {native: {hallo:'Welt'}}, (err)=>{
                        if (err) {
                            console.error(`Error - conn.emit extendObject '${id}': ${err}`);
                        } else {
                            console.log(`conn.emit extendObject '${id}': We are in callback and no error occurred`);
                        }
                    });
                }, 1000);


                /*        
                const id = '0_userdata.0.example_state';
                const val = {val:true, ack:true};

                conn.emit('setState', id, val, (err)=>{
                    if (err) {
                        console.error(`Error - conn.emit setState '${id}': ${err}`);
                    } else {
                        console.log(`conn.emit setState '${id}': We are in callback and no error occurred`);
                    }
                });
            */

            } catch (error) {
                console.error(`conn.on callback function - Unexpected error '${error}' - ${JSON.stringify(error)}`);
            }            

        });

    } catch (error) {
        console.error(`main() Unexpected error '${error}' - ${JSON.stringify(error)}`);
    }


}


/**
 * Promise Wrapping
 */


function setObjectAsync(path, obj) {
    return new Promise((resolve, reject) => {
        conn.emit('setObject', path, obj, (err)=>{
            if (err) {
                console.error(`setObjectAsync(): ${err}`);
                reject(false);
            } else {
                resolve(true);
            }
        });
    });
}

/**
 * @param {string} path - File path
 * @return {Promise<object|null>} object if successful, null if not.
 */
function getObjectAsync(path) {
    return new Promise((resolve, reject) => {
        conn.emit('getObject', path, (err, data)=>{
            if (err) {
                console.error(`getObjectAsync(): ${err}`);
                reject(null);
            } else {
                resolve(data);
            }
        });
    });
}
```

**Comment by Mic-M** [comment]
Please let me know if you need this test code as module for testing, then I will provide via Github. 
I have tested in two different modules now, but never works for some unknown reason.
But socket.io Adapter code looks good:
https://github.com/ioBroker/ioBroker.socketio/blob/523a681cffc77847286cad5c274f038559f26718/lib/socket.js#L971

**Comment by Apollon77** [comment]
So it means no callback is called and no error and such?

**Comment by foxriver76** [comment]
There are some functionalities that are only available if `allowAdmin` flag is used. This cannot be done in adapter config. IMHO it makes more sense to allow the methods, permissions are checked anyways and I can also mess up things with `setObject`, so we can allow the other methods too.

**Comment by foxriver76** [comment]
see #35

**Comment by Mic-M** [comment]
@Apollon77 
Correct

@foxriver76 
Thank you for your swift PR!

**Comment by Apollon77** [comment]
will be closed when we merge the PR

**Comment by Mic-M** [comment]
I see, thanks

**Comment by Apollon77** [comment]
@Mic-M sorry aber ich würde hier gern eine "Bremse" reinhauen ... bist Du am Mi im Dev Meeting? lets discuss it please:https://forum.iobroker.net/post/521435

**Comment by Mic-M** [comment]
@Apollon77 - am Mi kann ich leider nicht dabei sein (Family ruft). 
Ich verstehe deine Bedenken sehr gut (VIS, offene Ports, ...), echt ein wichtiger Punkt.
Mein Use Case ist ein npm-Modul (https://github.com/Jey-Cee/iobroker-drones) zum Ablösen des Windows-Control-Adapters.
Aber hatte da eh einen schnellen Workaround eingebaut: https://github.com/Jey-Cee/iobroker-drones/blob/a5472f070963e3add7d15cf1813de197e3726269/main.js#L301

**Comment by Apollon77** [comment]
Vllt antworte bitte im Meeting thread.

**Comment by Mic-M** [comment]
gerne, gerade getan

**Comment by Apollon77** [comment]
Wie gestern besprochen wollen wir das erst einmal nicht exposen - Einfacher ist socket.io via admin zu nutzen für Euren Anwendungsfall

**Comment by Mic-M** [comment]
Danke.
Mit admin meinst du den Admin-Adapter, richtig? https://github.com/ioBroker/ioBroker.admin
Wie kann ich denn darüber von einem externen npm-Modul socket.io nutzen?

**Comment by Apollon77** [comment]
admin bietet auch socket.io interface an. http://ip:8081/...
