### ISSUE TITLE
`requireLog` not working

### ISSUE THREAD

**Issue by nokxs** [ioBroker/ioBroker.socketio#39]
**`requireLog` not working**  
Emitting `requireLog`, as described in the readme, does not return and listening to `log` does not work. If the socket.io connection via Admin (Port 8081) is used, everything works as expected. 

Example code: 

```typescript
 registerForLogs() {
        if (this.client && this.isConnected) {
            this.client.on("log", (message: any) => {
                console.log(message);
            });

            this.client.emit("requireLog", true, (err: any) => {
                console.log(err);
            });
        }
    }
```

**To Reproduce**  
1. See exmple code.

**Expected behavior**  
Emitting `requireLog` either should lead to receiving Log-Messages or  the readme should be adjusted.

More details can be found in the ioBroker forum (in german): https://forum.iobroker.net/topic/40315/socket-io-log-ausgaben-empfangen.

**Comment by Apollon77** [comment]
Reason is that io-package.json of socket.io do not contain "logTransporter: true" ... so it can not work ...
@GermanBluefox Is the flag missing in io.package or is that an "admin only" feature? ;-)

**Comment by GermanBluefox** [comment]
> Reason is that io-package.json of socket.io do not contain "logTransporter: true" ... so it can not work ... @GermanBluefox Is the flag missing in io.package or is that an "admin only" feature? ;-)

It should be admin only feature

**Comment by GermanBluefox** [comment]
@nokxs Why do you want to read logs?

**Comment by nokxs** [comment]
I'm the author of https://github.com/nokxs/iobroker-javascript-vs-code-extension, which has the ability to show the log output of  scripts.

Actually I don't need this feature anymore because I'm connecting directly to the admin web socket, which is working just fine.
