### ISSUE TITLE
socket.io.js.map not found

### ISSUE THREAD

**Issue by GodHunter** [ioBroker/ioBroker.socketio#47]
Hallo,

ich habe seit dem Update auf eine Version > 3.0.12 das Problem das die Datei socket.io.js.map nicht mehr verfügbar ist. Die vollständige Fehlermeldung lautet:

DevTools failed to load SourceMap: Could not load content for http://192.168.178.4:8082/lib/js/socket.io.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Hierbei fällt mir auf, das er versucht auf Port 8082 zu verbinden, ist an sich freigegeben / weitergeleitet. Beim Aufruf via Browser (http://192.168.178.4:8082/lib/js/socket.io.js.map) erhalte ich die Meldung: File lib/js/socket.io.js.map not found: Not exists

Müsste er hier nicht ebenfalls auf Port 8084 gehen? Dort erhalte ich die Meldung: Not Implemented

Ich hab leider keine Ahnung von wo die Anweisung kommt die URL zu laden (http://192.168.178.4:8082/lib/js/socket.io.js.map).

**Comment by Apollon77** [comment]
Ja, wozu benötigst du das File? Oder geht es nur darum das es ein 404 ist ?

**Comment by GodHunter** [comment]
Sobald ich meine 3.0.12 auf eine höhere Version Update funktioniert keine Abfrage mehr. Evtl. gab es da auch größere Änderungen? Das ist aber die einzige Fehlermeldung die ich da erhalten.

Die Konsole gibt dann lediglich folgendes aus:

`2021-02-16T15:48:21.254Z Connected => authenticate
DevTools failed to load SourceMap: Could not load content for http://am-nas-01:8082/lib/js/socket.io.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
conn.js:264 2021-02-16T15:48:21.550Z Authenticated: true
index.php?display=stromverbrauch:319 connected
3data.js:429 `

**Comment by Apollon77** [comment]
Bitte conn.js updated, da gabs nen change ... example im Repo ist aktuaisiert

**Comment by GodHunter** [comment]
E voila, das wars. Danke für den Hinweis und die ganze Arbeit.
