### ISSUE TITLE
Can you please specify..

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.socketio#5]
Can you please provide some more information on this:

> (bluefox) Dropped support of old browsers. Please do not update if you have iPad 1 and so on.

I.e. I'm using 3 x IPAD2 as Display and like to know if they will continue working or not.

I asked at iobroker Forum but did not get a sufficient answer.

**Comment by winterson0** [comment]
I have an ipad2 also and after the update to 2.0.1 it does not work anymore.
So i downgrade to 1.8.5

**Comment by wendy2702** [comment]
Thanks for information.

**Comment by GermanBluefox** [comment]
Thank you for testing. So if you want to use your iPad. Please stay on 1.8.6

2018-04-30 22:58 GMT+02:00 wendy2702 <notifications@github.com>:

**Comment by wendy2702** [comment]
Just tested with IPAD 2 running at IOS 9.3.5 with Safari, Chrome and KioskPro (Free Version) and VIS is still working.
