### ISSUE TITLE
connect a socket.io-client to ioBroker 

### ISSUE THREAD

**Issue by mitch85** [ioBroker/ioBroker.socketio#56]
Hi!, i try to connect an existing nodejs app to iobroker via socket.io. In the ioBroker logs i see the client is connected but on the client i don't get an "connect". What is wrong?
```
let socket = io.connect(url, {
  query: "key=nokey",
  "reconnection limit": 10000,
  "max reconnection attempts": Infinity,
  reconnection: false,
  upgrade: false,
  rememberUpgrade: true,
  transports: ["websocket"],
});

socket.on("connect", () => {
  socket.emit("name", "mobile.0");
  console.log("connected");
});
```

**Comment by Apollon77** [comment]
Did you synced your code with the example provided here in this repo?

**Comment by mitch85** [comment]
> Did you synced your code with the example provided here in this repo?

yes, the "connect" part is from the example.

**Comment by 5v3n-08** [comment]
I have the same issue with this settings:


![Bildschirmfoto 2021-05-01 um 12 35 53](https://user-images.githubusercontent.com/52165058/116780034-1cbfdc80-aa7a-11eb-88cf-1c8b1b422d79.png)
![Bildschirmfoto 2021-05-01 um 12 36 04](https://user-images.githubusercontent.com/52165058/116780020-0d409380-aa7a-11eb-8cfd-a7e1f91795a1.png)
![Bildschirmfoto 2021-05-01 um 12 37 35](https://user-images.githubusercontent.com/52165058/116780024-10d41a80-aa7a-11eb-8097-ef7e93db9f5d.png)

**Comment by GermanBluefox** [comment]
It is VERY important to read always socket.io.js from server `http://localhost:8084/socket.io/socket.io.js` and not to have socket.io.js in application.
Just tested the example and everything works fine:
![image](https://user-images.githubusercontent.com/4582016/186376425-e738aea5-8d52-438e-9d26-adb45e9f7dce.png)
