### ISSUE TITLE
Socket.io version in README

### ISSUE THREAD

**Issue by fennsen64** [ioBroker/ioBroker.socketio#6]
Hi Bluefox, 
,,2.1.1 (2018-06-09):    (bluefox) Used socket.io Version 1.7.**2**"
I guess this is a typo and should be 1.7.5 ?
-> io-package.json:
,, "2.1.1": {
+                "en": "Used socket.io Version 1.7.5\nAuthentication porblem fixed",
+                "de": "Gebrauchte socket.io Version 1.7.5\nAuthentifizierungsfehler behoben",
+                "ru": "Используемая версия socket.io 1.7.5\nФиксированная аутентификация",
+                "pt": "Usado socket.io versão 1.7.5\nAutenticação porble fixo",
+                "nl": "Gebruikte socket.io versie 1.7.5\nAuthentificatie porblem vastgesteld",
+                "fr": "Version socket.io utilisée 1.7.5\nPorblem d'authentification fixé",
+                "it": "Usato socket.io Versione 1.7.5\nIl problema è stato risolto con l'autenticazione",
+                "es": "Utiliza socket.io versión 1.7.5\nAutenticación porblem fija",
+                "pl": "Użyty socket.io Wersja 1.7.5\nNaprawiono porblem uwierzytelniania"
+            },
             "2.1.0": {
                 "en": "Used socket.io Version 1.7.4",
                 "de": "Gebrauchte socket.io Version 1.7.4",

**Comment by GermanBluefox** [comment]
It is an error in socketio io-package.json. It must be everywhere 1.7.2

ср, 13 июн. 2018 г., 12:07 fennsen64 <notifications@github.com>:
