### ISSUE TITLE
Make Root Url Customizeable

### ISSUE THREAD

**Issue by alexpthe1** [ioBroker/ioBroker.socketio#86]
While setting up a ReverseProxy i have seen that some requests are (obviuosly) hardcoded to the root.
For Example:

/?sid=XXXXXXXX&name=admin from socket.io:91
/login?href=#tab-intro
It would be great to customize the root directory so these requests dont have to be re-written

**Comment by GermanBluefox** [comment]
All these requests do the web clients and not the server/socket. Isn't it?
