### ISSUE TITLE
getStates produces invalid callback error

### ISSUE THREAD

**Issue by hedav85** [ioBroker/ioBroker.socketio#93]
**Describe the bug**  
I use the Socket.io API in my own website. I can connect to the Socket.io adapter and I recieve state changes. But if I use the getStates function I get the error `invalid callback` in IO Broker log and never got a response from the adapter.

**To Reproduce**  
I used the code from the example.
```javascript
servConn.init({
            name: 'mobile.0',  // optional - default 'vis.0'
            connLink: this.host,  // optional URL of the socket.io adapter
            socketSession: ''           // optional - used by authentication
        }, {
            onConnChange: (isConnected) => {
                if (isConnected) {
                    console.log('connected');

                    servConn.getStates('*', (err, _states) => {
                        if (err) {
                            console.err(err);
                        } else {
                            var count = 0;
                            for (var id in _states) {
                                count++;
                            }
                            console.log('Received ' + count + ' states.');
                            states = _states;
                        }
                    });
                } else {
                    console.log('disconnected');
                }
            }
...
```

**Expected behavior**  
`getStates` gets the requested states from the adapter.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/16241555/150843574-01442874-66df-4985-ab27-0091ca13e560.png)

**Versions:**  
 - Adapter version: 3.1.5

For IO Broker I use the official docker image from https://github.com/buanet/ioBroker.docker
 - JS-Controller version: 3.3.15
 - Node version: 14.18.3
 - Operating system: <os-name>

**Comment by Apollon77** [comment]
Hm ... If admin logs this then you connect to the admin socket connection and not to the one from this adapter vis web ... so this seems to be the first issue. And from there you get teh reason because admin uses a different arameter structure. Please use the correct websocket endpoint!

**Comment by hedav85** [comment]
@Apollon77 thanks for the hint. I was connecting to the wrong endpoint. Now it works! Thank you!
